## Intro to NumPy 
NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays (https://en.wikipedia.org/wiki/NumPy).

Numpy is incredibly fast, as it has bindings to C libraries. 

In [32]:
import numpy as np

## Creation of NumPy array
### From a list

In [33]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

In [34]:
print(type(a_list))
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [35]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
a_2D = np.array(matrix)

### Using built-in methods

In [36]:
np.arange(0, 10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0, 10, 2) # np.arange(start, stop, step)

array([0, 2, 4, 6, 8])

In [38]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.linspace(0, 10, 20) # np.linspace(start, stop, num=50) 

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Random 

### uniform
Return an array of the given shape with random samples from a uniform distribution

In [59]:
np.random.uniform(0, 1, 5) # (low, high, size)

array([0.84725174, 0.6235637 , 0.38438171, 0.29753461, 0.05671298])

### randn
Return samples from the “standard normal” distribution.

In [42]:
np.random.randn(2,2) # standard normal (Gaussian) distribution of mean 0 and variance 1

array([[-2.2683282 ,  1.33354538],
       [-0.84272405,  1.96992445]])

### normal

In [64]:
mu, sigma = 1, 0.5 # mean and standard deviation
np.random.normal(mu, sigma, size = (3, 2))

array([[0.88798061, 0.78990831],
       [1.49991485, 1.21551707],
       [0.67454356, 0.25062981]])

### multivariate normal

In [66]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[0.45763642, 0.28032762],
        [0.42109121, 3.42694855]],

       [[1.27699691, 2.78966713],
        [1.32207411, 2.70039238]],

       [[1.38871663, 1.95873614],
        [1.29588432, 1.57472001]]])

### randint
Return random integers 

In [43]:
np.random.randint(1, 100, 5) # randint(low, high=None, size=None)

array([71, 89, 89, 13, 59])

### seed()
The seed() method is used to initialize the random number generator.

In [44]:
np.random.seed(0)  

### Operations

In [45]:
arr = np.arange(0, 10) 
arr_r = arr.reshape(2, 5)
print('arr: ')
print(arr)
print('arr_r: ')
print(arr_r)

arr: 
[0 1 2 3 4 5 6 7 8 9]
arr_r: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
my_arr = np.random.randint(1, 100, 10)
print(my_arr)

[89 40  3 18 72 50 89 52  1 45]


In [46]:
my_arr.max()

89

In [47]:
my_arr.argmax()

0

In [50]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [51]:
arr_1 + arr_2

array([5, 7, 9])

In [52]:
arr_1 * arr_2

array([ 4, 10, 18])

In [53]:
np.exp(arr_1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [54]:
np.log(arr_1)

array([0.        , 0.69314718, 1.09861229])