In [16]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np


In [17]:
T = 8 # time steps number
D = 2 # number of features(x, y)
M = 3 # LSTM units

In [18]:
x = np.random.randn(1, T, D)

## LSTM

In [19]:
inputs = keras.Input(shape=(T, D))
outputs = layers.LSTM(M, return_state = False, return_sequences = False)(inputs)
model = keras.Model(inputs=inputs, outputs=outputs)

In [20]:
model.predict(x) # last hidden state

array([[0.06841979, 0.04265887, 0.06859066]], dtype=float32)

In [21]:
outputs = layers.LSTM(M, return_state = False, return_sequences = True)(inputs)
model = keras.Model(inputs=inputs, outputs=outputs)

In [22]:
model.predict(x) # hidden state for each time step

array([[[ 0.13034558,  0.00457507, -0.00544272],
        [ 0.02890224,  0.0283402 ,  0.08653542],
        [-0.0512187 ,  0.01794821,  0.02619833],
        [-0.00624662,  0.00849469, -0.02631349],
        [ 0.14113317,  0.03136048,  0.05204686],
        [ 0.19158371,  0.01618731, -0.1102612 ],
        [ 0.00785958,  0.00306422, -0.07641591],
        [ 0.05773866,  0.01412194, -0.14621845]]], dtype=float32)

In [23]:
outputs = layers.LSTM(M, return_state = True, return_sequences = False)(inputs)
model = keras.Model(inputs=inputs, outputs=outputs)

In [24]:
model.predict(x) # output, hidden state and cell state (output = hidden state) for last time step

[array([[ 0.06961417, -0.17860271,  0.00923122]], dtype=float32),
 array([[ 0.06961417, -0.17860271,  0.00923122]], dtype=float32),
 array([[ 0.12502725, -0.34291422,  0.01860526]], dtype=float32)]

In [25]:
outputs = layers.LSTM(M, return_state = True, return_sequences = True)(inputs)
model = keras.Model(inputs=inputs, outputs=outputs)

In [26]:
model.predict(x) # returns the hidden state for each input time step, then separately, the hidden state output for 
                #last time step and cell state for last time step

[array([[[-0.00823668,  0.14966483, -0.08951403],
         [-0.03480426, -0.0137319 ,  0.08857161],
         [ 0.02519928, -0.07480928,  0.19494462],
         [ 0.01438387, -0.01710937,  0.07214712],
         [-0.00756933,  0.11693407, -0.05415456],
         [ 0.01213067,  0.23120733, -0.19735646],
         [ 0.24803387, -0.06564764,  0.04705572],
         [ 0.06095553, -0.09667318,  0.00662024]]], dtype=float32),
 array([[ 0.06095553, -0.09667318,  0.00662024]], dtype=float32),
 array([[ 0.16657215, -0.16547987,  0.01580743]], dtype=float32)]

## Bidirectional LSTM

In [27]:
outputs = layers.Bidirectional(layers.LSTM(M, return_state = False, return_sequences = False))(inputs)
model = keras.Model(inputs=inputs, outputs=outputs)

In [28]:
model.predict(x) # 2xh

array([[-0.10552286,  0.07142535, -0.08294625,  0.01777819, -0.0391664 ,
        -0.00660032]], dtype=float32)

## Stacked LSTM

In [29]:
outputs_layer_1 = layers.LSTM(M, return_state = False, return_sequences = True)(inputs)
outputs_layer_2 = layers.LSTM(M, return_state = False, return_sequences = False)(outputs_layer_1)
model = keras.Model(inputs=inputs, outputs=outputs_layer_2)

In [30]:
model.predict(x)

array([[ 0.02571977, -0.02697229,  0.00339985]], dtype=float32)